In [1]:
import pandas as pd

In [2]:
df_2009 = pd.read_csv("microdados_2009_limpo.csv", sep=";", encoding="latin-1")
df_2013 = pd.read_csv("microdados_2013_limpo.csv", sep=";", encoding="latin-1")
df_2016 = pd.read_csv("microdados_2016_limpo.csv", sep=";", encoding="latin-1")
df_2020 = pd.read_csv("microdados_2020_limpo.csv", sep=",", encoding="latin-1")
df_2021 = pd.read_csv("microdados_2021_limpo.csv", sep=",", encoding="latin-1")
df_2022 = pd.read_csv("microdados_2022_limpo.csv", sep=",", encoding="latin-1")
df_2023 = pd.read_csv("microdados_2023_limpo.csv", sep=",", encoding="latin-1")

dfs = [df_2009, df_2013, df_2016, df_2020, df_2021, df_2022, df_2023]

In [3]:
colunas_comuns = [col for col in df_2009.columns if all(col in df.columns for df in dfs)]

In [4]:
colunas_exclusivas = []
for df in dfs:
    for col in df.columns:
        if col not in colunas_comuns and col not in colunas_exclusivas:
            colunas_exclusivas.append(col)

In [5]:
ordem_final = colunas_comuns + colunas_exclusivas

In [6]:
df_unificado = pd.concat(dfs, ignore_index=True)
df_unificado = df_unificado[ordem_final]

In [7]:
df_unificado.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ST_CONCLUSAO,SG_UF_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,TP_COR_RACA,Q001,Q002,Q006,TP_ESCOLA,Q003,Q004
0,2009,5,F,1.0,RJ,459.6,410.4,536.6,556.9,575.0,A,B,E,B,NaN,NaN,NaN
1,2009,9,F,4.0,RJ,406.9,430.3,519.9,413.1,500.0,B,B,B,B,NaN,NaN,NaN
2,2009,7,F,1.0,RJ,432.3,527.7,541.2,464.4,700.0,B,C,F,C,NaN,NaN,NaN
3,2009,3,F,2.0,RJ,406.1,629.9,580.0,417.9,775.0,C,C,C,B,NaN,NaN,NaN
4,2009,11,F,1.0,RJ,430.8,424.6,457.8,560.3,625.0,A,C,C,C,NaN,NaN,NaN

In [8]:
df_unificado.tail()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ST_CONCLUSAO,SG_UF_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,TP_COR_RACA,Q001,Q002,Q006,TP_ESCOLA,Q003,Q004
19156456,2023,12,F,1.0,RS,568.6,605.2,598.2,496.8,500.0,1,B,B,D,1.0,D,D
19156457,2023,3,M,2.0,RS,476.2,542.9,545.2,530.5,600.0,1,E,E,F,2.0,D,D
19156458,2023,12,M,1.0,RS,566.2,605.6,613.7,547.3,540.0,1,C,E,F,1.0,F,F
19156459,2023,1,F,3.0,SP,377.2,535.6,610.6,644.4,640.0,1,F,F,F,1.0,B,B
19156460,2023,2,M,2.0,SP,515.7,539.0,536.0,569.0,600.0,1,G,G,N,3.0,E,E