In [1]:
import pandas as pd

In [2]:
ANO = 2025                              
arquivo_participantes = f"PARTICIPANTES_{ANO}.csv"  
arquivo_resultados = f"RESULTADOS_{ANO}.csv"

In [3]:
colunas_participantes = ["TP_SEXO","TP_COR_RACA","TP_FAIXA_ETARIA","SG_UF_PROVA","Q007","Q023",
            "TP_ST_CONCLUSAO","NU_ANO","Q001","Q002","Q003","Q004"]   

colunas_resultados = ["NU_NOTA_CN","NU_NOTA_CH","NU_NOTA_LC","NU_NOTA_MT","NU_NOTA_REDACAO"]

In [4]:
participantes = pd.read_csv(arquivo_participantes, sep=";", encoding="latin-1", usecols=colunas_participantes)
resultados = pd.read_csv(arquivo_resultados, sep=";", encoding="latin-1", usecols=colunas_resultados)

In [5]:
participantes = participantes.rename(columns={
    "Q007" : "Q006",
    "Q023" : "TP_ESCOLA"
})

In [6]:
participantes.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_COR_RACA,TP_ST_CONCLUSAO,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q006,TP_ESCOLA
0,2025,6,F,2,1,BA,C,F,A,A,B,A
1,2025,3,M,1,2,BA,B,E,C,B,D,A
2,2025,2,F,1,3,SP,E,E,D,D,F,C
3,2025,2,M,3,2,PI,D,F,D,D,B,D
4,2025,1,F,1,3,MT,G,G,E,E,Q,D

In [7]:
resultados.head()

   NU_NOTA_CN  NU_NOTA_CH  NU_NOTA_LC  NU_NOTA_MT  NU_NOTA_REDACAO
0       524.1       624.2       534.9       653.6            640.0
1         NaN         NaN         NaN         NaN              NaN
2       463.5       420.6       368.9       402.5              0.0
3         NaN         NaN         NaN         NaN              NaN
4       537.3       536.6       512.1       574.0            860.0

In [8]:
print(participantes.isna().sum())   
print(resultados.isna().sum())

NU_ANO             0
TP_FAIXA_ETARIA    0
TP_SEXO            0
TP_COR_RACA        0
TP_ST_CONCLUSAO    0
SG_UF_PROVA        0
Q001               0
Q002               0
Q003               0
Q004               0
Q006               0
TP_ESCOLA          0
dtype: int64
NU_NOTA_CN         1550436
NU_NOTA_CH         1353217
NU_NOTA_LC         1353217
NU_NOTA_MT         1550436
NU_NOTA_REDACAO    1353217
dtype: int64

In [9]:
participantes_limpo = participantes.dropna()  
resultados_limpo = resultados.dropna()

In [10]:
print(len(participantes), "->", len(participantes_limpo))   # linhas antes -> depois
print(len(participantes), "->", len(resultados_limpo))

4810772 -> 4810772
4810772 -> 3244348

In [11]:
participantes_limpo.to_csv(f"participantes_{ANO}_limpo.csv", index=False)  
resultados_limpo.to_csv(f"resultados_{ANO}_limpo.csv", index=False)

In [12]:
p = pd.read_csv("PARTICIPANTES_2025.csv", sep=";", encoding="latin-1", nrows=5)
r = pd.read_csv("RESULTADOS_2025.csv", sep=";", encoding="latin-1", nrows=5)
print(list(p.columns))
print(list(r.columns))

['NU_INSCRICAO', 'NU_ANO', 'TP_FAIXA_ETARIA', 'TP_SEXO', 'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_NACIONALIDADE', 'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'TP_ENSINO', 'IN_TREINEIRO', 'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 'Q001', 'Q002', 'Q003', 'Q004', 'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022', 'Q023']
['NU_SEQUENCIAL', 'NU_ANO', 'CO_ESCOLA', 'CO_MUNICIPIO_ESC', 'NO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC', 'TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC', 'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT', 'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC', 'CO_PROVA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH', 'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT', 'TP_LINGUA', 'TX_GABARITO_CN', 'TX_GABARITO_CH', 'TX_GABARITO_LC', 'TX_GABARITO_MT', 'TP_STATUS_REDACAO', 'NU_NOTA_COMP1', 'NU_NOTA_COMP2', 'NU_NOTA_COMP3', 'NU_NOTA_COMP4', 'NU_NOTA_COMP5', 'NU_NOTA_REDACAO', 'TP_STATUS_REDACAO_AV1', 'NU_NOTA_AV1', 'NU_NOTA_COMP1_AV1', 'NU_NOTA_COMP2_AV1', 'NU_NOTA_COMP3_AV1', 'NU_NOTA_COMP4_AV1', 'NU_NOTA_COMP5_AV1', 'TP_STATUS_REDACAO_AV2', 'NU_NOTA_AV2', 'NU_NOTA_COMP1_AV2', 'NU_NOTA_COMP2_AV2', 'NU_NOTA_COMP3_AV2', 'NU_NOTA_COMP4_AV2', 'NU_NOTA_COMP5_AV2', 'TP_STATUS_REDACAO_AV3', 'NU_NOTA_AV3', 'NU_NOTA_COMP1_AV3', 'NU_NOTA_COMP2_AV3', 'NU_NOTA_COMP3_AV3', 'NU_NOTA_COMP4_AV3', 'NU_NOTA_COMP5_AV3', 'TP_STATUS_REDACAO_AV4', 'NU_NOTA_AV4', 'NU_NOTA_COMP1_AV4', 'NU_NOTA_COMP2_AV4', 'NU_NOTA_COMP3_AV4', 'NU_NOTA_COMP4_AV4', 'NU_NOTA_COMP5_AV4']