In [64]:
import pandas as pd

In [65]:
ANO = 2024
arquivo_participantes = f"PARTICIPANTES_{ANO}.csv"
arquivo_resultados = f"RESULTADOS_{ANO}.csv"

In [66]:
colunas_participantes = ["TP_SEXO","TP_COR_RACA","TP_FAIXA_ETARIA","SG_UF_PROVA","Q007","Q023",
            "TP_ST_CONCLUSAO","NU_ANO","Q001","Q002","Q003","Q004"]   

colunas_resultados = ["NU_NOTA_CN","NU_NOTA_CH","NU_NOTA_LC","NU_NOTA_MT","NU_NOTA_REDACAO"]

In [67]:
participantes = pd.read_csv(arquivo_participantes, sep=";", encoding="latin-1", usecols=colunas_participantes)
resultados = pd.read_csv(arquivo_resultados, sep=";", encoding="latin-1", usecols=colunas_resultados)

In [68]:
participantes.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_COR_RACA,TP_ST_CONCLUSAO,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q007,Q023
0,2024,5,F,1,1,RS,F,F,C,D,C,A
1,2024,11,F,1,1,RS,B,C,A,D,E,A
2,2024,11,F,1,1,RS,H,F,F,D,J,A
3,2024,3,F,3,2,RS,B,B,B,B,C,A
4,2024,16,M,1,1,RS,B,B,C,C,A,A

In [69]:
resultados.head()

   NU_NOTA_CN  NU_NOTA_CH  NU_NOTA_LC  NU_NOTA_MT  NU_NOTA_REDACAO
0       436.8       377.8       423.4       427.1            300.0
1       521.9       601.9       605.5       689.2            920.0
2       363.0       548.4       557.2       456.4            480.0
3       550.7       553.8       605.9       629.1            740.0
4         NaN         NaN         NaN         NaN              NaN

In [70]:
print(participantes.isna().sum())
print(resultados.isna().sum())

NU_ANO             0
TP_FAIXA_ETARIA    0
TP_SEXO            0
TP_COR_RACA        0
TP_ST_CONCLUSAO    0
SG_UF_PROVA        0
Q001               0
Q002               0
Q003               0
Q004               0
Q007               0
Q023               0
dtype: int64
NU_NOTA_CN         1327963
NU_NOTA_CH         1164989
NU_NOTA_LC         1164989
NU_NOTA_MT         1327963
NU_NOTA_REDACAO    1164989
dtype: int64

In [71]:
participantes_limpo = participantes.dropna()
resultados_limpo = resultados.dropna()

In [72]:
print(len(participantes), "->", len(participantes_limpo))
print(len(resultados), "->", len(resultados_limpo))

4332944 -> 4332944
4332944 -> 2990093

In [73]:
participantes_limpo.to_csv(f"participantes_{ANO}_limpo.csv",index=False)
resultados_limpo.to_csv(f"resultados_{ANO}_limpo.csv",index=False)

In [74]:
p = pd.read_csv("PARTICIPANTES_2024.csv", sep=";", encoding="latin-1", nrows=5)
r = pd.read_csv("RESULTADOS_2024.csv", sep=";", encoding="latin-1", nrows=5)

print(list(p.columns))
print(list(r.columns))

['NU_INSCRICAO', 'NU_ANO', 'TP_FAIXA_ETARIA', 'TP_SEXO', 'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_NACIONALIDADE', 'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'TP_ENSINO', 'IN_TREINEIRO', 'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 'Q001', 'Q002', 'Q003', 'Q004', 'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022', 'Q023']
['NU_SEQUENCIAL', 'NU_ANO', 'CO_ESCOLA', 'CO_MUNICIPIO_ESC', 'NO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC', 'TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC', 'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT', 'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC', 'CO_PROVA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH', 'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT', 'TP_LINGUA', 'TX_GABARITO_CN', 'TX_GABARITO_CH', 'TX_GABARITO_LC', 'TX_GABARITO_MT', 'TP_STATUS_REDACAO', 'NU_NOTA_COMP1', 'NU_NOTA_COMP2', 'NU_NOTA_COMP3', 'NU_NOTA_COMP4', 'NU_NOTA_COMP5', 'NU_NOTA_REDACAO']