In [11]:
import pandas as pd

In [12]:
df_2009 = pd.read_csv("microdados_2009_limpo.csv", sep=";", encoding="latin-1")
df_2013 = pd.read_csv("microdados_2013_limpo.csv", sep=";", encoding="latin-1")
df_2016 = pd.read_csv("microdados_2016_limpo.csv", sep=";", encoding="latin-1")

dfs = [df_2009, df_2013, df_2016]

In [13]:
colunas_comuns = [col for col in df_2009.columns if all(col in df.columns for df in dfs)]

In [14]:
colunas_2009_exc = [col for col in df_2009.columns if col not in colunas_comuns]
colunas_2013_exc = [col for col in df_2013.columns if col not in colunas_comuns and col not in colunas_2009_exc]
colunas_2016_exc = [col for col in df_2016.columns if col not in colunas_comuns and col not in colunas_2009_exc and col not in colunas_2013_exc]

In [15]:
ordem_final = colunas_comuns + colunas_2009_exc + colunas_2013_exc + colunas_2016_exc

In [16]:
df_unificado = pd.concat(dfs, ignore_index=True)
df_unificado = df_unificado[ordem_final]

In [17]:
df_unificado.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ST_CONCLUSAO,SG_UF_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,TP_COR_RACA,Q001,Q002,Q006,TP_ESCOLA,Q003,Q004
0,2009,5,F,1.0,RJ,459.6,410.4,536.6,556.9,575.0,A,B,E,B,NaN,NaN,NaN
1,2009,9,F,4.0,RJ,406.9,430.3,519.9,413.1,500.0,B,B,B,B,NaN,NaN,NaN
2,2009,7,F,1.0,RJ,432.3,527.7,541.2,464.4,700.0,B,C,F,C,NaN,NaN,NaN
3,2009,3,F,2.0,RJ,406.1,629.9,580.0,417.9,775.0,C,C,C,B,NaN,NaN,NaN
4,2009,11,F,1.0,RJ,430.8,424.6,457.8,560.3,625.0,A,C,C,C,NaN,NaN,NaN

In [18]:
df_unificado.tail()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ST_CONCLUSAO,SG_UF_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,TP_COR_RACA,Q001,Q002,Q006,TP_ESCOLA,Q003,Q004
9333959,2016,13,F,3.0,MG,432.7,514.5,421.3,449.4,420.0,1,C,C,C,1.0,B,B
9333960,2016,14,M,1.0,RO,436.2,575.0,484.7,467.3,400.0,3,B,B,K,1.0,A,F
9333961,2016,13,M,3.0,BA,486.1,440.2,394.7,435.3,340.0,3,D,B,E,1.0,C,B
9333962,2016,14,F,1.0,ES,420.6,597.3,595.5,457.6,560.0,3,C,A,D,1.0,C,B
9333963,2016,2,F,2.0,MS,438.3,509.6,537.9,541.7,520.0,1,G,F,C,2.0,C,C